In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/ML Micro Projects/data/raw/ner_dataset.csv', encoding='latin1')

In [4]:
df.shape

(1048575, 4)

In [5]:
df.head()

    Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [6]:
df.tail()

        Sentence #       Word  POS Tag
1048570        NaN       they  PRP   O
1048571        NaN  responded  VBD   O
1048572        NaN         to   TO   O
1048573        NaN        the   DT   O
1048574        NaN     attack   NN   O

Exploratory Data Analysis

In [7]:
df.isnull().sum()

Sentence #    1000616
Word               10
POS                 0
Tag                 0
dtype: int64

In [8]:
df.dropna(subset=['Word'],inplace=True)

In [9]:
df.isnull().sum()

Sentence #    1000616
Word                0
POS                 0
Tag                 0
dtype: int64

In [10]:
df['Sentence #']

0          Sentence: 1
1                  NaN
2                  NaN
3                  NaN
4                  NaN
              ...
1048570            NaN
1048571            NaN
1048572            NaN
1048573            NaN
1048574            NaN
Name: Sentence #, Length: 1048565, dtype: object

In [11]:
df['Word']

0              Thousands
1                     of
2          demonstrators
3                   have
4                marched
               ...
1048570             they
1048571        responded
1048572               to
1048573              the
1048574           attack
Name: Word, Length: 1048565, dtype: object

In [12]:
df['Word'].nunique()

35177

In [13]:
df['POS'].unique()

array(['NNS', 'IN', 'VBP', 'VBN', 'NNP', 'TO', 'VB', 'DT', 'NN', 'CC',
       'JJ', '.', 'VBD', 'WP', '``', 'CD', 'PRP', 'VBZ', 'POS', 'VBG',
       'RB', ',', 'WRB', 'PRP$', 'MD', 'WDT', 'JJR', ':', 'JJS', 'WP$',
       'RP', 'PDT', 'NNPS', 'EX', 'RBS', 'LRB', 'RRB', '$', 'RBR', ';',
       'UH', 'FW'], dtype=object)

In [14]:
df['Tag'].unique()

array(['O', 'B-geo', 'B-gpe', 'B-per', 'I-geo', 'B-org', 'I-org', 'B-tim',
       'B-art', 'I-art', 'I-per', 'I-gpe', 'I-tim', 'B-nat', 'B-eve',
       'I-eve', 'I-nat'], dtype=object)

In [15]:
def get_dict_map(data, token_or_tag):
    tok2idx = {}
    idx2tok = {}
    if token_or_tag == 'token':
        vocab = set(data['Word'].to_list())
    else:
        vocab = set(data['Tag'].to_list())
    
    idx2tok = {idx:tok for  idx, tok in enumerate(vocab)}
    tok2idx = {tok:idx for  idx, tok in enumerate(vocab)}
    return tok2idx, idx2tok

In [16]:
token2idx, idx2token = get_dict_map(df, 'token')
tag2idx, idx2tag = get_dict_map(df, 'tag')

In [17]:
df['Word_idx'] = df['Word'].map(token2idx)
df['Tag_idx'] = df['Tag'].map(tag2idx)

In [18]:
df

          Sentence #           Word  POS Tag  Word_idx  Tag_idx
0        Sentence: 1      Thousands  NNS   O      7186       11
1                NaN             of   IN   O     17793       11
2                NaN  demonstrators  NNS   O      2383       11
3                NaN           have  VBP   O     24548       11
4                NaN        marched  VBN   O     31963       11
...              ...            ...  ...  ..       ...      ...
1048570          NaN           they  PRP   O      3437       11
1048571          NaN      responded  VBD   O      2954       11
1048572          NaN             to   TO   O     21075       11
1048573          NaN            the   DT   O     15383       11
1048574          NaN         attack   NN   O     18004       11

[1048565 rows x 6 columns]

In [19]:
df_fillna = df.fillna(method='ffill', axis=0)

/var/folders/4b/f46tx7f94tddgdzqfc22ctw80000gn/T/ipykernel_3369/587763615.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_fillna = df.fillna(method='ffill', axis=0)

In [20]:
df_fillna

              Sentence #           Word  POS Tag  Word_idx  Tag_idx
0            Sentence: 1      Thousands  NNS   O      7186       11
1            Sentence: 1             of   IN   O     17793       11
2            Sentence: 1  demonstrators  NNS   O      2383       11
3            Sentence: 1           have  VBP   O     24548       11
4            Sentence: 1        marched  VBN   O     31963       11
...                  ...            ...  ...  ..       ...      ...
1048570  Sentence: 47959           they  PRP   O      3437       11
1048571  Sentence: 47959      responded  VBD   O      2954       11
1048572  Sentence: 47959             to   TO   O     21075       11
1048573  Sentence: 47959            the   DT   O     15383       11
1048574  Sentence: 47959         attack   NN   O     18004       11

[1048565 rows x 6 columns]

In [21]:
# Groupby and collect columns
df_group = df_fillna.groupby(
    ['Sentence #'], as_index=False
)[['Word', 'POS', 'Tag', 'Word_idx', 'Tag_idx']].agg(lambda x: list(x))

In [22]:
df_group

,Sentence #,Word,POS,Tag,Word_idx,Tag_idx
0,Sentence: 1,"[Thousands, of, demonstrators, have, marched, ...","[NNS, IN, NNS, VBP, VBN, IN, NNP, TO, VB, DT, ...","[O, O, O, O, O, O, B-geo, O, O, O, O, O, B-geo...","[7186, 17793, 2383, 24548, 31963, 34094, 18452...","[11, 11, 11, 11, 11, 11, 1, 11, 11, 11, 11, 11..."
1,Sentence: 10,"[Iranian, officials, say, they, expect, to, ge...","[JJ, NNS, VBP, PRP, VBP, TO, VB, NN, TO, JJ, J...","[B-gpe, O, O, O, O, O, O, O, O, O, O, O, O, O,...","[9572, 6574, 5673, 3437, 9161, 21075, 8490, 19...","[7, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11..."
2,Sentence: 100,"[Helicopter, gunships, Saturday, pounded, mili...","[NN, NNS, NNP, VBD, JJ, NNS, IN, DT, NNP, JJ, ...","[O, O, B-tim, O, O, O, O, O, B-geo, O, O, O, O...","[6934, 20780, 26565, 31603, 9488, 33697, 23931...","[11, 11, 8, 11, 11, 11, 11, 11, 1, 11, 11, 11,..."
3,Sentence: 1000,"[They, left, after, a, tense, hour-long, stand...","[PRP, VBD, IN, DT, NN, JJ, NN, IN, NN, NNS, .]","[O, O, O, O, O, O, O, O, O, O, O]","[23216, 20779, 7127, 251, 1533, 29745, 8444, 2...","[11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11]"
4,Sentence: 10000,"[U.N., relief, coordinator, Jan, Egeland, said...","[NNP, NN, NN, NNP, NNP, VBD, NNP, ,, NNP, ,, J...","[B-geo, O, O, B-per, I-per, O, B-tim, O, B-geo...","[8184, 21295, 21396, 7716, 10784, 9139, 20967,...","[1, 11, 11, 14, 5, 11, 8, 11, 1, 11, 7, 11, 7,..."
...,...,...,...,...,...,...
47944,Sentence: 9995,"[Opposition, leader, Mir, Hossein, Mousavi, ha...","[NNP, NN, NNP, NNP, NNP, VBZ, VBN, PRP, VBZ, T...","[O, O, O, B-per, I-per, O, O, O, O, O, O, O, O...","[1436, 6794, 23643, 25209, 18569, 6012, 9139, ...","[11, 11, 11, 14, 5, 11, 11, 11, 11, 11, 11, 11..."
47945,Sentence: 9996,"[On, Thursday, ,, Iranian, state, media, publi...","[IN, NNP, ,, JJ, NN, NNS, VBN, DT, NN, IN, DT,...","[O, B-tim, O, B-gpe, O, O, O, O, O, O, O, O, B...","[20550, 21023, 3435, 9572, 14546, 4068, 13658,...","[11, 8, 11, 7, 11, 11, 11, 11, 11, 11, 11, 11,..."
47946,Sentence: 9997,"[Following, Iran, 's, disputed, June, 12, elec...","[VBG, NNP, POS, JJ, NNP, CD, NNS, ,, NNS, NNS,...","[O, B-geo, O, O, B-tim, I-tim, O, O, O, O, O, ...","[34516, 13846, 15180, 1869, 18184, 32261, 2158...","[11, 1, 11, 11, 8, 12, 11, 11, 11, 11, 11, 11,..."
47947,Sentence: 9998,"[Since, then, ,, authorities, have, held, publ...","[IN, RB, ,, NNS, VBP, VBN, JJ, NNS, IN, DT, VB...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[24185, 23151, 3435, 2114, 24548, 24284, 1691,...","[11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 1..."
47948,Sentence: 9999,"[The, United, Nations, is, praising, the, use,...","[DT, NNP, NNP, VBZ, VBG, DT, NN, IN, JJ, NNS, ...","[O, B-org, I-org, O, O, O, O, O, O, O, O, O, O...","[3280, 8350, 32047, 11992, 14518, 15383, 30523...","[11, 0, 15, 11, 11, 11, 11, 11, 11, 11, 11, 11..."

In [28]:
from sklearn.model_selection import train_test_split
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

In [29]:
def get_pad_train_test_val(data_group, data):

    #get max token and tag length
    n_token = len(list(set(data['Word'].to_list())))
    n_tag = len(list(set(data['Tag'].to_list())))

    #Pad tokens (X var)    
    tokens = data_group['Word_idx'].tolist()
    maxlen = max([len(s) for s in tokens])
    pad_tokens = pad_sequences(tokens, maxlen=maxlen, dtype='int32', padding='post', value= n_token - 1)

    #Pad Tags (y var) and convert it into one hot encoding
    tags = data_group['Tag_idx'].tolist()
    pad_tags = pad_sequences(tags, maxlen=maxlen, dtype='int32', padding='post', value= tag2idx["O"])
    n_tags = len(tag2idx)
    pad_tags = [to_categorical(i, num_classes=n_tags) for i in pad_tags]
    
    #Split train, test and validation set
    tokens_, test_tokens, tags_, test_tags = train_test_split(pad_tokens, pad_tags, test_size=0.1, train_size=0.9, random_state=2020)
    train_tokens, val_tokens, train_tags, val_tags = train_test_split(tokens_,tags_,test_size = 0.25,train_size =0.75, random_state=2020)

    print(
        'train_tokens length:', len(train_tokens),
        '\ntrain_tokens length:', len(train_tokens),
        '\ntest_tokens length:', len(test_tokens),
        '\ntest_tags:', len(test_tags),
        '\nval_tokens:', len(val_tokens),
        '\nval_tags:', len(val_tags),
    )
    
    return train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags

train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags = get_pad_train_test_val(df_group, df)

train_tokens length: 32365
train_tokens length: 32365
test_tokens length: 4795
test_tags: 4795
val_tokens: 10789
val_tags: 10789

In [30]:
import numpy as np
import tensorflow
from tensorflow.keras import Sequential, Model, Input
from tensorflow.keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional
from tensorflow.keras.utils import plot_model
from numpy.random import seed
seed(1)
tensorflow.random.set_seed(2)

In [31]:
input_dim = len(list(set(df['Word'].to_list())))+1
output_dim = 64
input_length = max([len(s) for s in df_group['Word_idx'].tolist()])
n_tags = len(tag2idx)

In [32]:
def get_bilstm_lstm_model():
    model = Sequential()

    # Add Embedding layer
    model.add(Embedding(input_dim=input_dim, output_dim=output_dim, input_length=input_length))

    # Add bidirectional LSTM
    model.add(Bidirectional(LSTM(units=output_dim, return_sequences=True, dropout=0.2, recurrent_dropout=0.2), merge_mode = 'concat'))

    # Add LSTM
    model.add(LSTM(units=output_dim, return_sequences=True, dropout=0.5, recurrent_dropout=0.5))

    # Add timeDistributed Layer
    model.add(TimeDistributed(Dense(n_tags, activation="relu")))

    #Optimiser 
    # adam = k.optimizers.Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)

    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    
    return model

In [33]:
def train_model(X, y, model):
    loss = list()
    for i in range(25):
        # fit model for one epoch on this sequence
        hist = model.fit(X, y, batch_size=1000, verbose=1, epochs=1, validation_split=0.2)
        loss.append(hist.history['loss'][0])
    return loss

In [34]:
results = pd.DataFrame()
model_bilstm_lstm = get_bilstm_lstm_model()
# Build the model by calling it on a batch of data before plotting
model_bilstm_lstm.build(input_shape=(None, input_length))
plot_model(model_bilstm_lstm)
results['with_add_lstm'] = train_model(train_tokens, np.array(train_tags), model_bilstm_lstm)

/Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed                │ ?                      │   0 (unbuilt) │
│ (TimeDistributed)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

You must install pydot (`pip install pydot`) for `plot_model` to work.
26/26 ━━━━━━━━━━━━━━━━━━━━ 71s 3s/step - accuracy: 0.8131 - loss: 1.8640 - val_accuracy: 0.9681 - val_loss: 0.3785
26/26 ━━━━━━━━━━━━━━━━━━━━ 66s 3s/step - accuracy: 0.9676 - loss: 0.3699 - val_accuracy: 0.9679 - val_loss: 0.3134
26/26 ━━━━━━━━━━━━━━━━━━━━ 66s 3s/step - accuracy: 0.9663 - loss: 0.3371 - val_accuracy: 0.9681 - val_loss: 0.2847
26/26 ━━━━━━━━━━━━━━━━━━━━ 60s 2s/step - accuracy: 0.9675 - loss: 0.3075 - val_accuracy: 0.9681 - val_loss: 0.2678
26/26 ━━━━━━━━━━━━━━━━━━━━ 63s 2s/step - accuracy: 0.9676 - loss: 0.2906 - val_accuracy: 0.9681 - val_loss: 0.2590
26/26 ━━━━━━━━━━━━━━━━━━━━ 66s 3s/step - accuracy: 0.9677 - loss: 0.2871 - val_accuracy: 0.9681 - val_loss: 0.2503
26/26 ━━━━━━━━━━━━━━━━━━━━ 62s 2s/step - accuracy: 0.9677 - loss: 0.2779 - val_accuracy: 0.9681 - val_loss: 0.2352
26/26 ━━━━━━━━━━━━━━━━━━━━ 62s 2s/step - accuracy: 0.9677 - loss: 0.2611 - val_accuracy: 0.9681 - val_loss: 0.2555
26/26 ━━━━━━━━━━━━━━━━━━━━ 60s 2s/step - accuracy: 0.9677 - loss: 0.3011 - val_accuracy: 0.9681 - val_loss: 0.2396
26/26 ━━━━━━━━━━━━━━━━━━━━ 66s 3s/step - accuracy: 0.9677 - loss: 0.2504 - val_accuracy: 0.9682 - val_loss: 0.1845
26/26 ━━━━━━━━━━━━━━━━━━━━ 66s 3s/step - accuracy: 0.9678 - loss: 0.2073 - val_accuracy: 0.9682 - val_loss: 0.1684
26/26 ━━━━━━━━━━━━━━━━━━━━ 62s 2s/step - accuracy: 0.9678 - loss: 0.2152 - val_accuracy: 0.9686 - val_loss: 0.1860
26/26 ━━━━━━━━━━━━━━━━━━━━ 61s 2s/step - accuracy: 0.9680 - loss: 0.2067 - val_accuracy: 0.9685 - val_loss: 0.1640
26/26 ━━━━━━━━━━━━━━━━━━━━ 61s 2s/step - accuracy: 0.9680 - loss: 0.1862 - val_accuracy: 0.9684 - val_loss: 0.1625
26/26 ━━━━━━━━━━━━━━━━━━━━ 488s 19s/step - accuracy: 0.9680 - loss: 0.1873 - val_accuracy: 0.9684 - val_loss: 0.1564
26/26 ━━━━━━━━━━━━━━━━━━━━ 61s 2s/step - accuracy: 0.9681 - loss: 0.1735 - val_accuracy: 0.9685 - val_loss: 0.1567
26/26 ━━━━━━━━━━━━━━━━━━━━ 800s 32s/step - accuracy: 0.9681 - loss: 0.1715 - val_accuracy: 0.9685 - val_loss: 0.1370
26/26 ━━━━━━━━━━━━━━━━━━━━ 66s 3s/step - accuracy: 0.9682 - loss: 0.1579 - val_accuracy: 0.9686 - val_loss: 0.1356
26/26 ━━━━━━━━━━━━━━━━━━━━ 65s 3s/step - accuracy: 0.9682 - loss: 0.1509 - val_accuracy: 0.9687 - val_loss: 0.1331
26/26 ━━━━━━━━━━━━━━━━━━━━ 67s 3s/step - accuracy: 0.9683 - loss: 0.1530 - val_accuracy: 0.9687 - val_loss: 0.1223
26/26 ━━━━━━━━━━━━━━━━━━━━ 67s 3s/step - accuracy: 0.9683 - loss: 0.1428 - val_accuracy: 0.9688 - val_loss: 0.1226
26/26 ━━━━━━━━━━━━━━━━━━━━ 68s 3s/step - accuracy: 0.9684 - loss: 0.1357 - val_accuracy: 0.9688 - val_loss: 0.1166
26/26 ━━━━━━━━━━━━━━━━━━━━ 67s 3s/step - accuracy: 0.9684 - loss: 0.1281 - val_accuracy: 0.9689 - val_loss: 0.1158
26/26 ━━━━━━━━━━━━━━━━━━━━ 66s 3s/step - accuracy: 0.9685 - loss: 0.1248 - val_accuracy: 0.9690 - val_loss: 0.1117
26/26 ━━━━━━━━━━━━━━━━━━━━ 68s 3s/step - accuracy: 0.9686 - loss: 0.1211 - val_accuracy: 0.9691 - val_loss: 0.1103

In [35]:
model_bilstm_lstm.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 104, 64)        │     2,251,392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 104, 128)       │        66,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 104, 64)        │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed                │ (None, 104, 17)        │         1,105 │
│ (TimeDistributed)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,103,861 (27.10 MB)

 Trainable params: 2,367,953 (9.03 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 4,735,908 (18.07 MB)

In [41]:
pip install spacy

Collecting spacy
  Downloading spacy-3.8.7-cp312-cp312-macosx_11_0_arm64.whl.metadata (27 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.13-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.2 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.11-cp312-cp312-macosx_11_0_arm64.whl.metadata (8.5 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.10-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.6-cp312-cp312-macosx_11_0_arm64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.5.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy)
  Using cached weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy)
  Using cached typer-0.16.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from spacy) (2.32.4)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Using cached pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
Collecting jinja2 (from spacy)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: setuptools in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from spacy) (25.0)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy)
  Using cached langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy)
  Using cached language_data-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading pydantic_core-2.33.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.8 kB)
Requirement already satisfied: typing-extensions>=4.12.2 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.14.1)
Collecting typing-inspection>=0.4.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached typing_inspection-0.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.7.9)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.3.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Using cached confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Collecting click>=8.0.0 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading click-8.2.1-py3-none-any.whl.metadata (2.5 kB)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=10.11.0 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.0.0)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy)
  Using cached cloudpathlib-0.21.1-py3-none-any.whl.metadata (14 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.1.0->spacy)
  Using cached smart_open-7.3.0.post1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: wrapt in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.2)
Collecting marisa-trie>=1.1.0 (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy)
  Downloading marisa_trie-1.2.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.0 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages (from jinja2->spacy) (3.0.2)
Downloading spacy-3.8.7-cp312-cp312-macosx_11_0_arm64.whl (5.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 1.0 MB/s eta 0:00:0000:0100:010m
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.11-cp312-cp312-macosx_11_0_arm64.whl (42 kB)
Using cached langcodes-3.5.0-py3-none-any.whl (182 kB)
Downloading murmurhash-1.0.13-cp312-cp312-macosx_11_0_arm64.whl (26 kB)
Downloading preshed-3.0.10-cp312-cp312-macosx_11_0_arm64.whl (126 kB)
Using cached pydantic-2.11.7-py3-none-any.whl (444 kB)
Downloading pydantic_core-2.33.2-cp312-cp312-macosx_11_0_arm64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 424.4 kB/s eta 0:00:00a 0:00:01
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.1-cp312-cp312-macosx_11_0_arm64.whl (634 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 634.7/634.7 kB 986.0 kB/s eta 0:00:00a 0:00:01
Downloading thinc-8.3.6-cp312-cp312-macosx_11_0_arm64.whl (839 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 839.4/839.4 kB 1.2 MB/s eta 0:00:00a 0:00:01
Downloading blis-1.3.0-cp312-cp312-macosx_11_0_arm64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 1.5 MB/s eta 0:00:00a 0:00:01
Using cached confection-0.1.5-py3-none-any.whl (35 kB)
Using cached typer-0.16.0-py3-none-any.whl (46 kB)
Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Using cached weasel-0.4.1-py3-none-any.whl (50 kB)
Using cached cloudpathlib-0.21.1-py3-none-any.whl (52 kB)
Using cached smart_open-7.3.0.post1-py3-none-any.whl (61 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading click-8.2.1-py3-none-any.whl (102 kB)
Using cached language_data-1.3.0-py3-none-any.whl (5.4 MB)
Downloading marisa_trie-1.2.1-cp312-cp312-macosx_11_0_arm64.whl (174 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached typing_inspection-0.4.1-py3-none-any.whl (14 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Installing collected packages: cymem, wasabi, typing-inspection, spacy-loggers, spacy-legacy, smart-open, shellingham, pydantic-core, murmurhash, marisa-trie, jinja2, cloudpathlib, click, catalogue, blis, annotated-types, srsly, pydantic, preshed, language-data, typer, langcodes, confection, weasel, thinc, spacy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26/26 [spacy]m25/26 [spacy]ge-data]
Successfully installed annotated-types-0.7.0 blis-1.3.0 catalogue-2.0.10 click-8.2.1 cloudpathlib-0.21.1 confection-0.1.5 cymem-2.0.11 jinja2-3.1.6 langcodes-3.5.0 language-data-1.3.0 marisa-trie-1.2.1 murmurhash-1.0.13 preshed-3.0.10 pydantic-2.11.7 pydantic-core-2.33.2 shellingham-1.5.4 smart-open-7.3.0.post1 spacy-3.8.7 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.1 thinc-8.3.6 typer-0.16.0 typing-inspection-0.4.1 wasabi-1.1.3 weasel-0.4.1
Note: you may need to restart the kernel to use updated packages.

In [42]:
#Download the spaCy model if not already present
# import spacy.cli
# spacy.cli.download("en_core_web_sm")

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 867.1 kB/s eta 0:00:0000:0100:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [15]:
help(displacy)

Help on package spacy.displacy in spacy:

NAME
    spacy.displacy - spaCy's built in visualization suite for dependencies and named entities.

DESCRIPTION
    DOCS: https://spacy.io/api/top-level#displacy
    USAGE: https://spacy.io/usage/visualizers

PACKAGE CONTENTS
    render
    templates

FUNCTIONS
    app(environ, start_response)

    get_doc_settings(doc: spacy.tokens.doc.Doc) -> Dict[str, Any]

    parse_deps(orig_doc: Union[spacy.tokens.doc.Doc, spacy.tokens.span.Span], options: Dict[str, Any] = {}) -> Dict[str, Any]
        Generate dependency parse in {'words': [], 'arcs': []} format.

        orig_doc (Union[Doc, Span]): Document to parse.
        options (Dict[str, Any]): Dependency parse specific visualisation options.
        RETURNS (dict): Generated dependency parse keyed by words and arcs.

    parse_ents(doc: spacy.tokens.doc.Doc, options: Dict[str, Any] = {}) -> Dict[str, Any]
        Generate named entities in [{start: i, end: i, label: 'label'}] format.

        doc (Doc): Document to parse.
        options (Dict[str, Any]): NER-specific visualisation options.
        RETURNS (dict): Generated entities keyed by text (original text) and ents.

    parse_spans(doc: spacy.tokens.doc.Doc, options: Dict[str, Any] = {}) -> Dict[str, Any]
        Generate spans in [{start_token: i, end_token: i, label: 'label'}] format.

        doc (Doc): Document to parse.
        options (Dict[str, any]): Span-specific visualisation options.
        RETURNS (dict): Generated span types keyed by text (original text) and spans.

    render(docs: Union[Iterable[Union[spacy.tokens.doc.Doc, spacy.tokens.span.Span, dict]], spacy.tokens.doc.Doc, spacy.tokens.span.Span, dict], style: str = 'dep', page: bool = False, minify: bool = False, jupyter: Optional[bool] = None, options: Dict[str, Any] = {}, manual: bool = False) -> str
        Render displaCy visualisation.

        docs (Union[Iterable[Union[Doc, Span, dict]], Doc, Span, dict]]): Document(s) to visualise.
            a 'dict' is only allowed here when 'manual' is set to True
        style (str): Visualisation style, 'dep' or 'ent'.
        page (bool): Render markup as full HTML page.
        minify (bool): Minify HTML markup.
        jupyter (bool): Override Jupyter auto-detection.
        options (dict): Visualiser-specific options, e.g. colors.
        manual (bool): Don't parse `Doc` and instead expect a dict/list of dicts.
        RETURNS (str): Rendered SVG or HTML markup.

        DOCS: https://spacy.io/api/top-level#displacy.render
        USAGE: https://spacy.io/usage/visualizers

    serve(docs: Union[Iterable[spacy.tokens.doc.Doc], spacy.tokens.doc.Doc], style: str = 'dep', page: bool = True, minify: bool = False, options: Dict[str, Any] = {}, manual: bool = False, port: int = 5000, host: str = '0.0.0.0', auto_select_port: bool = False) -> None
        Serve displaCy visualisation.

        docs (list or Doc): Document(s) to visualise.
        style (str): Visualisation style, 'dep' or 'ent'.
        page (bool): Render markup as full HTML page.
        minify (bool): Minify HTML markup.
        options (dict): Visualiser-specific options, e.g. colors.
        manual (bool): Don't parse `Doc` and instead expect a dict/list of dicts.
        port (int): Port to serve visualisation.
        host (str): Host to serve visualisation.
        auto_select_port (bool): Automatically select a port if the specified port is in use.

        DOCS: https://spacy.io/api/top-level#displacy.serve
        USAGE: https://spacy.io/usage/visualizers

    set_render_wrapper(func: Callable[[str], str]) -> None
        Set an optional wrapper function that is called around the generated
        HTML markup on displacy.render. This can be used to allow integration into
        other platforms, similar to Jupyter Notebooks that require functions to be
        called around the HTML. It can also be used to implement custom callbacks
        on render, or to embed the visualization in a custom page.

        func (callable): Function to call around markup before rendering it. Needs
            to take one argument, the HTML markup, and should return the desired
            output of displacy.render.

DATA
    Callable = typing.Callable
        Deprecated alias to collections.abc.Callable.

        Callable[[int], str] signifies a function that takes a single
        parameter of type int and returns a str.

        The subscription syntax must always be used with exactly two
        values: the argument list and the return type.
        The argument list must be a list of types, a ParamSpec,
        Concatenate or ellipsis. The return type must be a single type.

        There is no syntax to indicate optional or keyword arguments;
        such function types are rarely used as callback types.

    Dict = typing.Dict
        A generic version of dict.

    Iterable = typing.Iterable
        A generic version of collections.abc.Iterable.

    Optional = typing.Optional
        Optional[X] is equivalent to Union[X, None].

    RENDER_WRAPPER = None
    Union = typing.Union
        Union type; Union[X, Y] means either X or Y.

        On Python 3.10 and higher, the | operator
        can also be used to denote unions;
        X | Y means the same thing to the type checker as Union[X, Y].

        To define a union, use e.g. Union[int, str]. Details:
        - The arguments must be types and there must be at least one.
        - None as an argument is a special case and is replaced by
          type(None).
        - Unions of unions are flattened, e.g.::

            assert Union[Union[int, str], float] == Union[int, str, float]

        - Unions of a single argument vanish, e.g.::

            assert Union[int] == int  # The constructor actually returns int

        - Redundant arguments are skipped, e.g.::

            assert Union[int, str, int] == Union[int, str]

        - When comparing unions, the argument order is ignored, e.g.::

            assert Union[int, str] == Union[str, int]

        - You cannot subclass or instantiate a union.
        - You can use Optional[X] as a shorthand for Union[X, None].

FILE
    /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages/spacy/displacy/__init__.py

In [17]:
import spacy
from spacy import displacy
nlp = spacy.load('en_core_web_sm')
text = nlp('Hi, My name is Aman Kharwal \n I am from India \n I want to work with Google \n Steve Jobs is My Inspiration')
displacy.render(text, style='ent', jupyter=True)

ImportError: cannot import name 'display' from 'IPython.core.display' (/Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages/IPython/core/display.py)

Found existing installation: jupyter 1.1.0
Uninstalling jupyter-1.1.0:
  Would remove:
    /Users/anshugangwar/Desktop/Anshu/Data Science Portfolio/.venv/lib/python3.12/site-packages/jupyter-1.1.0.dist-info/*
Proceed (Y/n)? ^C
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install ipykernel==6.29.5 ipython==7.23.1
pip install jupyter==1.1.0
# ...

SyntaxError: invalid syntax (1582826095.py, line 1)

In [9]:
jupyter --version

NameError: name 'jupyter' is not defined